### ISSUE TITLE
log gives quoted output

### ISSUE THREAD

**Issue by TuningGuide** [steveukx/git-js#81] opened 2016-03-30 19:52 UTC
```
	gitRepo
		.log(function(err, log) {
			console.log(log);
		});
```
Gives me hashes with prepended ' and author_email's with appended '. And also the stdoutput is quoted with '

**Comment by steveukx** [comment] 2016-03-31 07:29
Is this a duplicate of #78?

**Comment by TuningGuide** [comment] 2016-03-31 07:37
Oh. yes it is. I must have installed it 21 days ago ^^,

**Comment by steveukx** [comment] 2016-03-31 07:39
No problem!

**Closed by steveukx** 2016-03-31 07:39 UTC
